-- MySQL Script generated by MySQL Workbench
-- Mon Feb  3 15:39:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema argosbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema argosbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `argosbd` DEFAULT CHARACTER SET utf8 ;
USE `argosbd` ;

-- -----------------------------------------------------
-- Table `argosbd`.`operacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`operacao` (
  `idoperacao` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_operecao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idoperacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `argosbd`.`acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`acao` (
  `idacao` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_acao` VARCHAR(100) NULL DEFAULT NULL,
  `dt_inicio` DATE NULL DEFAULT NULL,
  `dt_termino` DATE NULL DEFAULT NULL,
  `hr_inicio` TIME NULL DEFAULT NULL,
  `hr_termino` TIME NULL DEFAULT NULL,
  `latitude` DECIMAL(10,8) NULL DEFAULT NULL,
  `longitude` DECIMAL(11,8) NULL DEFAULT NULL,
  `status` VARCHAR(30) NULL DEFAULT NULL,
  `idoperacao` INT(11) NOT NULL,
  PRIMARY KEY (`idacao`),
  INDEX `fk_acao_operacao1_idx` (`idoperacao` ASC) VISIBLE,
  CONSTRAINT `fk_acao_operacao1`
    FOREIGN KEY (`idoperacao`)
    REFERENCES `argosbd`.`operacao` (`idoperacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `argosbd`.`grupo_indicador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`grupo_indicador` (
  `idgrupo_indicador` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_grupo` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`idgrupo_indicador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`indicador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`indicador` (
  `idindicador` INT(11) NOT NULL AUTO_INCREMENT,
  `indicador` VARCHAR(60) NULL DEFAULT NULL,
  `idgrupo_indicador` INT(11) NOT NULL,
  PRIMARY KEY (`idindicador`),
  INDEX `fk_indicador_grupo_indicador1_idx` (`idgrupo_indicador` ASC) VISIBLE,
  CONSTRAINT `fk_indicador_grupo_indicador1`
    FOREIGN KEY (`idgrupo_indicador`)
    REFERENCES `argosbd`.`grupo_indicador` (`idgrupo_indicador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`acao_indicador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`acao_indicador` (
  `idacao_indicadro` INT(11) NOT NULL AUTO_INCREMENT,
  `idindicador` INT(11) NOT NULL,
  `idacao` INT(11) NOT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idacao_indicadro`),
  INDEX `fk_acao_indicadro_indicador1_idx` (`idindicador` ASC) VISIBLE,
  INDEX `fk_acao_indicadro_acao1_idx` (`idacao` ASC) VISIBLE,
  CONSTRAINT `fk_acao_indicadro_acao1`
    FOREIGN KEY (`idacao`)
    REFERENCES `argosbd`.`acao` (`idacao`),
  CONSTRAINT `fk_acao_indicadro_indicador1`
    FOREIGN KEY (`idindicador`)
    REFERENCES `argosbd`.`indicador` (`idindicador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`instituicao` (
  `idinstituicao` INT(11) NOT NULL AUTO_INCREMENT,
  `instituicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idinstituicao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`acao_instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`acao_instituicao` (
  `idacao_instituicao` INT(11) NOT NULL AUTO_INCREMENT,
  `idinstituicao` INT(11) NOT NULL,
  `idacao` INT(11) NOT NULL,
  `responsavel` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idacao_instituicao`),
  INDEX `fk_acao_instituicao_instituicao1_idx` (`idinstituicao` ASC) VISIBLE,
  INDEX `fk_acao_instituicao_acao1_idx` (`idacao` ASC) VISIBLE,
  CONSTRAINT `fk_acao_instituicao_acao1`
    FOREIGN KEY (`idacao`)
    REFERENCES `argosbd`.`acao` (`idacao`),
  CONSTRAINT `fk_acao_instituicao_instituicao1`
    FOREIGN KEY (`idinstituicao`)
    REFERENCES `argosbd`.`instituicao` (`idinstituicao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`ocorrencia` (
  `idocorrencia` INT(11) NOT NULL AUTO_INCREMENT,
  `ocorrencia` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`idocorrencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`acao_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`acao_ocorrencia` (
  `idacao_ocorrencia` INT(11) NOT NULL AUTO_INCREMENT,
  `idacao` INT(11) NOT NULL,
  `idocorrencia` INT(11) NOT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idacao_ocorrencia`),
  INDEX `fk_acao_ocorrencia_acao1_idx` (`idacao` ASC) VISIBLE,
  INDEX `fk_acao_ocorrencia_ocorrencia1_idx` (`idocorrencia` ASC) VISIBLE,
  CONSTRAINT `fk_acao_ocorrencia_acao1`
    FOREIGN KEY (`idacao`)
    REFERENCES `argosbd`.`acao` (`idacao`),
  CONSTRAINT `fk_acao_ocorrencia_ocorrencia1`
    FOREIGN KEY (`idocorrencia`)
    REFERENCES `argosbd`.`ocorrencia` (`idocorrencia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`recurso` (
  `idrecurso` INT(11) NOT NULL AUTO_INCREMENT,
  `recurso` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`idrecurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`acao_recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`acao_recurso` (
  `idacao_recurso` INT(11) NOT NULL AUTO_INCREMENT,
  `idacao` INT(11) NOT NULL,
  `idrecurso` INT(11) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  PRIMARY KEY (`idacao_recurso`),
  INDEX `fk_acao_recurso_acao1_idx` (`idacao` ASC) VISIBLE,
  INDEX `fk_acao_recurso_recurso1_idx` (`idrecurso` ASC) VISIBLE,
  CONSTRAINT `fk_acao_recurso_acao1`
    FOREIGN KEY (`idacao`)
    REFERENCES `argosbd`.`acao` (`idacao`),
  CONSTRAINT `fk_acao_recurso_recurso1`
    FOREIGN KEY (`idrecurso`)
    REFERENCES `argosbd`.`recurso` (`idrecurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`status` (
  `idstatus` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstatus`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`acao_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`acao_status` (
  `idacao_status` INT(11) NOT NULL AUTO_INCREMENT,
  `idacao` INT(11) NOT NULL,
  `idstatus` INT(11) NOT NULL,
  PRIMARY KEY (`idacao_status`),
  INDEX `fk_acao_status_acao1_idx` (`idacao` ASC) VISIBLE,
  INDEX `fk_acao_status_status1_idx` (`idstatus` ASC) VISIBLE,
  CONSTRAINT `fk_acao_status_acao1`
    FOREIGN KEY (`idacao`)
    REFERENCES `argosbd`.`acao` (`idacao`),
  CONSTRAINT `fk_acao_status_status1`
    FOREIGN KEY (`idstatus`)
    REFERENCES `argosbd`.`status` (`idstatus`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`municipio` (
  `idmunicipio` INT(11) NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmunicipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`municipio_acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`municipio_acao` (
  `idmunicipio_acao` INT(11) NOT NULL AUTO_INCREMENT,
  `idacao` INT(11) NOT NULL,
  `idmunicipio` INT(11) NOT NULL,
  PRIMARY KEY (`idmunicipio_acao`),
  INDEX `fk_municipio_acao_acao1_idx` (`idacao` ASC) VISIBLE,
  INDEX `fk_municipio_acao_municipio1_idx` (`idmunicipio` ASC) VISIBLE,
  CONSTRAINT `fk_municipio_acao_acao1`
    FOREIGN KEY (`idacao`)
    REFERENCES `argosbd`.`acao` (`idacao`),
  CONSTRAINT `fk_municipio_acao_municipio1`
    FOREIGN KEY (`idmunicipio`)
    REFERENCES `argosbd`.`municipio` (`idmunicipio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`territorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`territorio` (
  `idterritorio` INT(11) NOT NULL AUTO_INCREMENT,
  `territorio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idterritorio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`territorio_acao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`territorio_acao` (
  `idterritorio_acao` INT(11) NOT NULL,
  `idacao` INT(11) NOT NULL,
  `idterritorio` INT(11) NOT NULL,
  PRIMARY KEY (`idterritorio_acao`),
  INDEX `fk_territorio_acao_acao1_idx` (`idacao` ASC) VISIBLE,
  INDEX `fk_territorio_acao_territorio1_idx` (`idterritorio` ASC) VISIBLE,
  CONSTRAINT `fk_territorio_acao_acao1`
    FOREIGN KEY (`idacao`)
    REFERENCES `argosbd`.`acao` (`idacao`),
  CONSTRAINT `fk_territorio_acao_territorio1`
    FOREIGN KEY (`idterritorio`)
    REFERENCES `argosbd`.`territorio` (`idterritorio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL DEFAULT NULL,
  `rg` VARCHAR(15) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `dt_nascimento` DATE NULL DEFAULT NULL,
  `senha` VARCHAR(128) NULL DEFAULT NULL,
  `contato` VARCHAR(45) NULL DEFAULT NULL,
  `idinstituicao` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_instituicao1_idx` (`idinstituicao` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_instituicao1`
    FOREIGN KEY (`idinstituicao`)
    REFERENCES `argosbd`.`instituicao` (`idinstituicao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `argosbd`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `argosbd`.`transacao` (
  `idtransacao` INT(11) NOT NULL AUTO_INCREMENT,
  `transacao` TEXT NULL DEFAULT NULL,
  `dt_transacao` TIMESTAMP NULL DEFAULT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idtransacao`),
  INDEX `fk_transacao_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_transacao_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `argosbd`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
